apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stock
type: Opaque
data:
  POSTGRES_PASSWORD: c3VwZXJwYXNz # base64(superpass)
  REPLICATION_PASSWORD: cmVwbGljYQ== # base64(replica)