apiVersion: v1
data:
  pg_hba.conf: |-
    host replication replicator 0.0.0.0/0 md5
    host all all 0.0.0.0/0 md5
  replica-config.conf: |-
    hot_standby = on
kind: ConfigMap
metadata:
  name: postgres-replica-configmap
