apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: stock
spec:
  serviceName: "postgres-replica"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: replicator
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REPLICATION_PASSWORD
          command:
            - "bash"
            - "-c"
            - |
              until pg_isready -h postgres-primary; do sleep 1; done;
              rm -rf /var/lib/postgresql/data/*
              PGPASSWORD=replica pg_basebackup -h postgres-primary -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R
              exec docker-entrypoint.sh postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}