apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: stock
spec:
  serviceName: "postgres-replica"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      initContainers:
        - name: init-perms
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 999:999 /var/lib/postgresql/data
              chmod 0700 /var/lib/postgresql/data
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-replica-configmap-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql/conf.d
          command:
            - "bash"
            - "-c"
            - |
              docker-entrypoint.sh postgres -c config_file=/etc/postgresql/conf.d/replica-config.conf
          securityContext:
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-replica-pvc
        - name: config
          configMap:
            name: postgres-replica-configmap
            items:
              - key: replica-config.conf
                path: replica-config.conf
              - key: pg_hba.conf
                path: pg_hba.conf