apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-replica-pv
  namespace: stock
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/postgres/deal