apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deal-service
    type: microservice
  name: service-depl
  namespace: deal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deal-service
      type: microservice
  strategy: {}
  template:
    metadata:
      labels:
        app: deal-service
        type: microservice
    spec:
      containers:
      - image: maximyakovlevvv/deal-service:latest
        name: deal-service
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: service-configmap
        imagePullPolicy: Always

