spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        response-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9876

resilience4j:
  circuitbreaker:
    instances:
      backendService:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always