app:
  authorization:
    header-name: "Authorization"
    header-prefix: "Bearer "
  headers:
    user-id: "X-User-ID"
    user-roles: "X-User-Roles"
  topics:
    stock-trade-events: stock-trade-events
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800