spring:
  application:
    name: authorization-service
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/myDatabase?authSource=admin
  grpc:
    server:
      port: 9091
    client:
      channels:
        local:
          address: 0.0.0.0:9090

server:
  port: 6789

app:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256