spring:
  application:
    name: deal-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/deal_service_db
    username: postgres
    password: password123
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/deal_service_db
    user: postgres
    password: password123
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework: INFO
    com:
      trading_platform: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka