spring:
  application:
    name: deal-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/deal_service_db
    username: postgres
    password: password123
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/deal_service_db
    user: postgres
    password: password123
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      batch-size: 1638400
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        linger.ms: 5
        request.timeout.ms: 60000
      compression-type: snappy
    listener:
      ack-mode: record
      poll-timeout: 150
    main:
      web-application-type: reactive
      allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework: INFO
    com:
      trading_platform: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka