spring:
  application:
    name: transaction-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/transaction_service_db
    username: postgres
    password: password123
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5434/transaction_service_db
    user: postgres
    password: password123
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fulfillment-store-assistant-${kafka.group-id.prefix}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      heartbeat-interval: 3000
      properties:
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
        max.poll.interval.ms: 30000
        max.partition.fetch.bytes: 1048576
      isolation-level: read_committed
    main:
      web-application-type: reactive
      allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework: INFO
    com:
      trading_platform: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka