apiVersion: v1
data:
  master-config.conf: |-
    wal_level = replica
    max_wal_senders = 10
    wal_keep_size = 64
  pg_hba.conf: |-
    host replication replicator 0.0.0.0/0 md5
    host all all 0.0.0.0/0 md5
kind: ConfigMap
metadata:
  name: postgres-master-configmap
  namespace: stock
