apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-deal-service-svc
  name: postgres-deal-service-svc
  namespace: deal
spec:
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-deal-service-depl
    type: database
  type: ClusterIP
status:
  loadBalancer: {}
