apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-deal-service-pv
  namespace: deal-service
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres/deal-service