version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=myDatabase
    volumes:
      - ./docker/mongodb/data:/data/db
    ports:
      - "27017:27017"
