apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool-depl
  namespace: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
        - name: pgpool
          image: bitnami/pgpool:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pgpool-configmap
