apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgpool-svc
  name: pgpool-svc
  namespace: stock
spec:
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pgpool-svc
  type: ClusterIP
